name: Build HuP Kernel

on:
  push:
    branches:
      - hup-fck
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ARCH: arm64
      CONFIG_FILE: vendor/lahaina-qgki_defconfig
      KBUILD_BUILD_HOST: Pão
      KBUILD_BUILD_USER: HotaruOs
      TC_DIR: tc
      CCACHE_DIR: ~/.ccache
      USE_CCACHE: 1
      KERNEL_NAME: HuP-Fck死

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc bison build-essential ccache curl flex git \
          libssl-dev libncurses-dev \
          python3 unzip zip

    - name: Setup ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ github.sha }}
        restore-keys: |
          ccache-

    - name: Clone AOSP Clang r18
      run: |
        if [ ! -d "${TC_DIR}" ]; then
          git clone --depth=1 -b 18 \
            https://gitlab.com/ThankYouMario/android_prebuilts_clang-standalone \
            ${TC_DIR}
        fi

    - name: Show Clang version
      run: |
        ${TC_DIR}/bin/clang --version

    - name: Setup KernelSU
      run: |
        curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: Export toolchain PATH
      run: |
        echo "PATH=$PWD/${TC_DIR}/bin:$PATH" >> $GITHUB_ENV

    - name: Generate defconfig
      run: |
        make -s \
          ARCH=${ARCH} \
          O=out \
          CC=clang \
          HOSTCC=clang \
          ${CONFIG_FILE} \
          LLVM=1 \
          LLVM_IAS=1 \
          -j$(nproc)

    - name: Compile kernel
      run: |
        make -j$(nproc) \
          O=out \
          ARCH=${ARCH} \
          CC="ccache clang" \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
          LLVM=1 \
          LLVM_IAS=1

    - name: Package AnyKernel
      run: |
        KERNEL_NAME="HuP-Fck"
        ZIP_NAME="${KERNEL_NAME}-$(date +"%d%m%Y-%H%M").zip"

        git clone -q https://github.com/HotaruOs/AnyKernel3 -b pão anykernel

        cp out/arch/arm64/boot/Image anykernel/
        cp out/arch/arm64/boot/dts/vendor/qcom/*.img anykernel/
        cat out/arch/arm64/boot/dts/vendor/qcom/lahaina-moto-base-v2.1.dtb out/arch/arm64/boot/dts/vendor/qcom/lahaina-moto-base.dtb > anykernel/dtb || abort "Failed to concatenate lahaina*.dtb to AnyKernel3 directory!"

        cd anykernel
        zip -r AnyKernel.zip *
        mv AnyKernel.zip ${ZIP_NAME}
        mv ${ZIP_NAME} ../

    - name: Upload kernel zip
      uses: actions/upload-artifact@v4
      with:
        name: HuP-Kernel
        path: |
          *.zip

    - name: Get last commit description only
      run: |
        COMMIT_DESC=$(git log -1 --pretty=%B | sed '1{/^$/d;};1d')
        
        if [ -z "$COMMIT_DESC" ]; then
        COMMIT_DESC="No detailed changelog provided."
        fi

        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$COMMIT_DESC" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Set release tag
      run: echo "RELEASE_TAG=build-$(date +'%d%m%Y-%H%M')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "${{ env.KERNEL_NAME }} - ${{ env.RELEASE_TAG }}"
        tag_name: ${{ env.RELEASE_TAG }}
        body: |
          🔧 **HuP Kernel Build**
           - Defconfig: lahaina-qgki
           - Clang: AOSP r18
           - Root: KernelSU (rsuntk)

            ## 📝 Changelog
            ${{ env.CHANGELOG }}
        files: |
           *.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    
    - name: Get latest release asset
      uses: robinraju/release-downloader@v1.10
      with:
        latest: true
        fileName: "*.zip"

    - name: Debug downloaded files
      run: |
        echo "Workspace:"
        pwd
        ls -lh
        
    - name: Upload to Telegram
      run: |
       FILE=$(ls *.zip | head -n 1)
       echo "Uploading $FILE to Telegram"
       curl -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument" \
       -F chat_id="${{ secrets.TG_CHAT_ID }}" \
       -F document=@"$FILE" \
       -F parse_mode=HTML \
       -F caption="🔥 <b>HuP Kernel</b>
       📦 <b>Build:</b> $(date +"%d/%m/%Y %H:%M")
       📲 <b>Root:</b> KernelSU (rsuntk)
       🛠 <b>Clang:</b> AOSP r18
       📝 <b>Changelog</b>
       <pre>${{ env.CHANGELOG }}</pre>"
